{
 "title": "Lynx - Polaris",
 "tags": [
  "lynx",
  "polaris"
 ],
 "templating": {
  "list": [
   { "name": "DS_PROM", "query": "prometheus" },
   { "name": "rate_interval", "query": "1m,5m,15m" },
   { "name": "job", "query": "label_values(up, job)" },
   {
    "name": "instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   },
   {
    "name": "operation",
    "query": "label_values(polaris_sdk_operations_total, operation)"
   },
   {
    "name": "service",
    "query": "label_values(polaris_service_discovery_total, service)"
   },
   {
    "name": "namespace",
    "query": "label_values(polaris_service_discovery_total, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "SDK ops & errors",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (operation) (rate(polaris_sdk_operations_total{job=~\"$job\",instance=~\"$instance\",operation=~\"$operation\"}[$rate_interval]))",
     "legendFormat": "ops {{operation}}"
    },
    {
     "expr": "sum by (operation) (rate(polaris_sdk_errors_total{job=~\"$job\",instance=~\"$instance\",operation=~\"$operation\"}[$rate_interval]))",
     "legendFormat": "err {{operation}}"
    }
   ]
  },
  {
   "title": "SDK op duration (p95)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate(polaris_sdk_operations_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation=~\"$operation\"}[$rate_interval])))",
     "legendFormat": "p95 {{operation}}"
    }
   ]
  },
  {
   "title": "Service discovery ops",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (service,namespace) (rate(polaris_service_discovery_total{job=~\"$job\",instance=~\"$instance\",service=~\"$service\",namespace=~\"$namespace\"}[$rate_interval]))",
     "legendFormat": "{{service}}/{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate limit",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (service,namespace) (rate(polaris_rate_limit_requests_total{job=~\"$job\",instance=~\"$instance\",service=~\"$service\",namespace=~\"$namespace\"}[$rate_interval]))",
     "legendFormat": "req {{service}}/{{namespace}}"
    },
    {
     "expr": "sum by (service,namespace) (rate(polaris_rate_limit_rejected_total{job=~\"$job\",instance=~\"$instance\",service=~\"$service\",namespace=~\"$namespace\"}[$rate_interval]))",
     "legendFormat": "rej {{service}}/{{namespace}}"
    }
   ]
  }
 ]
}