// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.0
// source: nacos.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Nacos configuration
type Nacos struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server addresses (comma-separated, e.g., "127.0.0.1:8848,127.0.0.1:8849")
	ServerAddresses string `protobuf:"bytes,1,opt,name=server_addresses,json=serverAddresses,proto3" json:"server_addresses,omitempty"`
	// Namespace ID
	NamespaceId string `protobuf:"bytes,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	// Namespace name (alternative to namespace_id)
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Username for authentication
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	// Password for authentication
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	// Access key for authentication
	AccessKey string `protobuf:"bytes,6,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	// Secret key for authentication
	SecretKey string `protobuf:"bytes,7,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	// Service instance weight (default: 1.0)
	Weight float64 `protobuf:"fixed64,8,opt,name=weight,proto3" json:"weight,omitempty"`
	// Service instance metadata
	Metadata map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Enable service registration
	EnableRegister bool `protobuf:"varint,10,opt,name=enable_register,json=enableRegister,proto3" json:"enable_register,omitempty"`
	// Enable service discovery
	EnableDiscovery bool `protobuf:"varint,11,opt,name=enable_discovery,json=enableDiscovery,proto3" json:"enable_discovery,omitempty"`
	// Enable configuration management
	EnableConfig bool `protobuf:"varint,12,opt,name=enable_config,json=enableConfig,proto3" json:"enable_config,omitempty"`
	// Connection timeout (in seconds)
	Timeout uint64 `protobuf:"varint,13,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Log level: debug, info, warn, error
	LogLevel string `protobuf:"bytes,14,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	// Log directory
	LogDir string `protobuf:"bytes,15,opt,name=log_dir,json=logDir,proto3" json:"log_dir,omitempty"`
	// Cache directory
	CacheDir string `protobuf:"bytes,16,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	// Notify timeout (in milliseconds)
	NotifyTimeout uint64 `protobuf:"varint,17,opt,name=notify_timeout,json=notifyTimeout,proto3" json:"notify_timeout,omitempty"`
	// Service configuration
	ServiceConfig *ServiceConfig `protobuf:"bytes,18,opt,name=service_config,json=serviceConfig,proto3" json:"service_config,omitempty"`
	// Additional configuration sources
	AdditionalConfigs []*ConfigSource `protobuf:"bytes,19,rep,name=additional_configs,json=additionalConfigs,proto3" json:"additional_configs,omitempty"`
	// Context path for Nacos server
	ContextPath string `protobuf:"bytes,20,opt,name=context_path,json=contextPath,proto3" json:"context_path,omitempty"`
	// Endpoint for Nacos server (alternative to server_addresses)
	Endpoint string `protobuf:"bytes,21,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Region ID
	RegionId      string `protobuf:"bytes,22,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nacos) Reset() {
	*x = Nacos{}
	mi := &file_nacos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nacos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nacos) ProtoMessage() {}

func (x *Nacos) ProtoReflect() protoreflect.Message {
	mi := &file_nacos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nacos.ProtoReflect.Descriptor instead.
func (*Nacos) Descriptor() ([]byte, []int) {
	return file_nacos_proto_rawDescGZIP(), []int{0}
}

func (x *Nacos) GetServerAddresses() string {
	if x != nil {
		return x.ServerAddresses
	}
	return ""
}

func (x *Nacos) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *Nacos) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Nacos) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Nacos) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Nacos) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Nacos) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Nacos) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Nacos) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Nacos) GetEnableRegister() bool {
	if x != nil {
		return x.EnableRegister
	}
	return false
}

func (x *Nacos) GetEnableDiscovery() bool {
	if x != nil {
		return x.EnableDiscovery
	}
	return false
}

func (x *Nacos) GetEnableConfig() bool {
	if x != nil {
		return x.EnableConfig
	}
	return false
}

func (x *Nacos) GetTimeout() uint64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Nacos) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *Nacos) GetLogDir() string {
	if x != nil {
		return x.LogDir
	}
	return ""
}

func (x *Nacos) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *Nacos) GetNotifyTimeout() uint64 {
	if x != nil {
		return x.NotifyTimeout
	}
	return 0
}

func (x *Nacos) GetServiceConfig() *ServiceConfig {
	if x != nil {
		return x.ServiceConfig
	}
	return nil
}

func (x *Nacos) GetAdditionalConfigs() []*ConfigSource {
	if x != nil {
		return x.AdditionalConfigs
	}
	return nil
}

func (x *Nacos) GetContextPath() string {
	if x != nil {
		return x.ContextPath
	}
	return ""
}

func (x *Nacos) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Nacos) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

// Service configuration for registration
type ServiceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service name
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Group name (default: DEFAULT_GROUP)
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// Cluster name (default: DEFAULT)
	Cluster string `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// Health check enabled
	HealthCheck bool `protobuf:"varint,4,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	// Health check interval (in seconds)
	HealthCheckInterval uint64 `protobuf:"varint,5,opt,name=health_check_interval,json=healthCheckInterval,proto3" json:"health_check_interval,omitempty"`
	// Health check timeout (in seconds)
	HealthCheckTimeout uint64 `protobuf:"varint,6,opt,name=health_check_timeout,json=healthCheckTimeout,proto3" json:"health_check_timeout,omitempty"`
	// Health check type: none, tcp, http, mysql
	HealthCheckType string `protobuf:"bytes,7,opt,name=health_check_type,json=healthCheckType,proto3" json:"health_check_type,omitempty"`
	// Health check URL (for http type)
	HealthCheckUrl string `protobuf:"bytes,8,opt,name=health_check_url,json=healthCheckUrl,proto3" json:"health_check_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_nacos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_nacos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_nacos_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceConfig) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ServiceConfig) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ServiceConfig) GetHealthCheck() bool {
	if x != nil {
		return x.HealthCheck
	}
	return false
}

func (x *ServiceConfig) GetHealthCheckInterval() uint64 {
	if x != nil {
		return x.HealthCheckInterval
	}
	return 0
}

func (x *ServiceConfig) GetHealthCheckTimeout() uint64 {
	if x != nil {
		return x.HealthCheckTimeout
	}
	return 0
}

func (x *ServiceConfig) GetHealthCheckType() string {
	if x != nil {
		return x.HealthCheckType
	}
	return ""
}

func (x *ServiceConfig) GetHealthCheckUrl() string {
	if x != nil {
		return x.HealthCheckUrl
	}
	return ""
}

// Configuration source for multi-config loading
type ConfigSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration data ID
	DataId string `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	// Configuration group (default: DEFAULT_GROUP)
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// Configuration format: yaml, json, properties, xml
	Format        string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSource) Reset() {
	*x = ConfigSource{}
	mi := &file_nacos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSource) ProtoMessage() {}

func (x *ConfigSource) ProtoReflect() protoreflect.Message {
	mi := &file_nacos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSource.ProtoReflect.Descriptor instead.
func (*ConfigSource) Descriptor() ([]byte, []int) {
	return file_nacos_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigSource) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigSource) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigSource) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_nacos_proto protoreflect.FileDescriptor

const file_nacos_proto_rawDesc = "" +
	"\n" +
	"\vnacos.proto\x12\x17lynx.plugins.nacos.conf\"\x96\a\n" +
	"\x05Nacos\x12)\n" +
	"\x10server_addresses\x18\x01 \x01(\tR\x0fserverAddresses\x12!\n" +
	"\fnamespace_id\x18\x02 \x01(\tR\vnamespaceId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"access_key\x18\x06 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\a \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06weight\x18\b \x01(\x01R\x06weight\x12H\n" +
	"\bmetadata\x18\t \x03(\v2,.lynx.plugins.nacos.conf.Nacos.MetadataEntryR\bmetadata\x12'\n" +
	"\x0fenable_register\x18\n" +
	" \x01(\bR\x0eenableRegister\x12)\n" +
	"\x10enable_discovery\x18\v \x01(\bR\x0fenableDiscovery\x12#\n" +
	"\renable_config\x18\f \x01(\bR\fenableConfig\x12\x18\n" +
	"\atimeout\x18\r \x01(\x04R\atimeout\x12\x1b\n" +
	"\tlog_level\x18\x0e \x01(\tR\blogLevel\x12\x17\n" +
	"\alog_dir\x18\x0f \x01(\tR\x06logDir\x12\x1b\n" +
	"\tcache_dir\x18\x10 \x01(\tR\bcacheDir\x12%\n" +
	"\x0enotify_timeout\x18\x11 \x01(\x04R\rnotifyTimeout\x12M\n" +
	"\x0eservice_config\x18\x12 \x01(\v2&.lynx.plugins.nacos.conf.ServiceConfigR\rserviceConfig\x12T\n" +
	"\x12additional_configs\x18\x13 \x03(\v2%.lynx.plugins.nacos.conf.ConfigSourceR\x11additionalConfigs\x12!\n" +
	"\fcontext_path\x18\x14 \x01(\tR\vcontextPath\x12\x1a\n" +
	"\bendpoint\x18\x15 \x01(\tR\bendpoint\x12\x1b\n" +
	"\tregion_id\x18\x16 \x01(\tR\bregionId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x02\n" +
	"\rServiceConfig\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\acluster\x18\x03 \x01(\tR\acluster\x12!\n" +
	"\fhealth_check\x18\x04 \x01(\bR\vhealthCheck\x122\n" +
	"\x15health_check_interval\x18\x05 \x01(\x04R\x13healthCheckInterval\x120\n" +
	"\x14health_check_timeout\x18\x06 \x01(\x04R\x12healthCheckTimeout\x12*\n" +
	"\x11health_check_type\x18\a \x01(\tR\x0fhealthCheckType\x12(\n" +
	"\x10health_check_url\x18\b \x01(\tR\x0ehealthCheckUrl\"U\n" +
	"\fConfigSource\x12\x17\n" +
	"\adata_id\x18\x01 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06formatB,Z*github.com/go-lynx/lynx/plugins/nacos/confb\x06proto3"

var (
	file_nacos_proto_rawDescOnce sync.Once
	file_nacos_proto_rawDescData []byte
)

func file_nacos_proto_rawDescGZIP() []byte {
	file_nacos_proto_rawDescOnce.Do(func() {
		file_nacos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nacos_proto_rawDesc), len(file_nacos_proto_rawDesc)))
	})
	return file_nacos_proto_rawDescData
}

var file_nacos_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nacos_proto_goTypes = []any{
	(*Nacos)(nil),         // 0: lynx.plugins.nacos.conf.Nacos
	(*ServiceConfig)(nil), // 1: lynx.plugins.nacos.conf.ServiceConfig
	(*ConfigSource)(nil),  // 2: lynx.plugins.nacos.conf.ConfigSource
	nil,                   // 3: lynx.plugins.nacos.conf.Nacos.MetadataEntry
}
var file_nacos_proto_depIdxs = []int32{
	3, // 0: lynx.plugins.nacos.conf.Nacos.metadata:type_name -> lynx.plugins.nacos.conf.Nacos.MetadataEntry
	1, // 1: lynx.plugins.nacos.conf.Nacos.service_config:type_name -> lynx.plugins.nacos.conf.ServiceConfig
	2, // 2: lynx.plugins.nacos.conf.Nacos.additional_configs:type_name -> lynx.plugins.nacos.conf.ConfigSource
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nacos_proto_init() }
func file_nacos_proto_init() {
	if File_nacos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nacos_proto_rawDesc), len(file_nacos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nacos_proto_goTypes,
		DependencyIndexes: file_nacos_proto_depIdxs,
		MessageInfos:      file_nacos_proto_msgTypes,
	}.Build()
	File_nacos_proto = out.File
	file_nacos_proto_goTypes = nil
	file_nacos_proto_depIdxs = nil
}
