{
 "title": "Lynx - Health",
 "tags": [
  "lynx",
  "health"
 ],
 "templating": {
  "list": [
   { "name": "DS_PROM", "query": "prometheus" },
   { "name": "job", "query": "label_values(up, job)" },
   {
    "name": "instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   },
   {
    "name": "plugin",
    "query": "label_values(plugin_health_status, plugin)"
   }
  ]
 },
 "panels": [
  {
   "title": "Plugin health status",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "plugin_health_status{job=~\"$job\",instance=~\"$instance\",plugin=~\"$plugin\"}",
     "legendFormat": "{{plugin}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "plugin_health_error_count{job=~\"$job\",instance=~\"$instance\",plugin=~\"$plugin\"}",
     "legendFormat": "{{plugin}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Last check ts",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "plugin_health_last_check_timestamp_seconds{job=~\"$job\",instance=~\"$instance\",plugin=~\"$plugin\"}",
     "legendFormat": "{{plugin}}/{{instance}}"
    }
   ]
  }
 ]
}