server:
  name: name
  version: v1.0.0
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s
  tracer:
    addr: http://localhost:14268/api/traces
  polaris:
    namespace: dev
    token: polaris-token
    weight: 100
    ttl: 5
    timeout: 5s
data:
  database:
    driver: mysql
    source: username:password@tcp(127.0.0.1:3306)/db_dev?parseTime=True
    min_conn: 50
    max_conn: 50
    max_idle_time: 30s
  redis:
    addr: '127.0.0.1:6379'
    password: 'password'
    db: 0
    dial_timeout: 3s
    read_timeout: 1s
    write_timeout: 1s