{
 "title": "Lynx Seata Distributed Transaction Dashboard",
 "tags": [
  "lynx",
  "seata",
  "distributed-transaction",
  "dtx",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROM", "query": "prometheus" },
   { "name": "rate_interval", "query": "1m,5m,15m" },
   { "name": "job", "query": "label_values(up, job)" },
   {
    "name": "instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Global Transactions",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(lynx_seata_global_transactions{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Global Transactions"
    }
   ]
  },
  {
   "title": "Transaction Commit Rate",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(lynx_seata_transactions_total{status=\"committed\",job=~\"$job\",instance=~\"$instance\"}[$rate_interval])) / sum(rate(lynx_seata_transactions_total{job=~\"$job\",instance=~\"$instance\"}[$rate_interval])) * 100",
     "legendFormat": "Commit Rate %"
    }
   ]
  },
  {
   "title": "Transaction Status Over Time",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(lynx_seata_transactions_total{status=\"committed\",job=~\"$job\",instance=~\"$instance\"}[$rate_interval]))",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(rate(lynx_seata_transactions_total{status=\"rollbacked\",job=~\"$job\",instance=~\"$instance\"}[$rate_interval]))",
     "legendFormat": "Rollbacked"
    },
    {
     "expr": "sum(rate(lynx_seata_transactions_total{status=\"timeout\",job=~\"$job\",instance=~\"$instance\"}[$rate_interval]))",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Branch Transactions",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(lynx_seata_branch_transactions{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Branch Transactions"
    }
   ]
  },
  {
   "title": "Resource Manager Connections",
   "type": "stat",
   "gridPos": { "x": 6, "y": 4, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(lynx_seata_rm_connections{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "RM Connections"
    }
   ]
  }
 ]
}